/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MissRouteImport } from './routes/miss'
import { Route as CandidatIdRouteImport } from './routes/candidat.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MissRoute = MissRouteImport.update({
  id: '/miss',
  path: '/miss',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatIdRoute = CandidatIdRouteImport.update({
  id: '/candidat/$id',
  path: '/candidat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/candidat/$id': typeof CandidatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/candidat/$id': typeof CandidatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/candidat/$id': typeof CandidatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/classement' | '/master' | '/miss' | '/candidat/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/classement' | '/master' | '/miss' | '/candidat/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/classement'
    | '/master'
    | '/miss'
    | '/candidat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClassementRoute: typeof ClassementRoute
  MasterRoute: typeof MasterRoute
  MissRoute: typeof MissRoute
  CandidatIdRoute: typeof CandidatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miss': {
      id: '/miss'
      path: '/miss'
      fullPath: '/miss'
      preLoaderRoute: typeof MissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidat/$id': {
      id: '/candidat/$id'
      path: '/candidat/$id'
      fullPath: '/candidat/$id'
      preLoaderRoute: typeof CandidatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClassementRoute: ClassementRoute,
  MasterRoute: MasterRoute,
  MissRoute: MissRoute,
  CandidatIdRoute: CandidatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
