/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassementRouteImport } from './routes/classement'
import { Route as MasterRouteImport } from './routes/master'
import { Route as MissRouteImport } from './routes/miss'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as CandidatIdRouteImport } from './routes/candidat.$id'
import { Route as PaymentConfirmationRouteImport } from './routes/payment.confirmation'
import { Route as ApiMonetbilWebhookRouteImport } from './routes/api/monetbil.webhook'
import { Route as ApiPayunitWebhookRouteImport } from './routes/api/payunit.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementRoute = ClassementRouteImport.update({
  id: '/classement',
  path: '/classement',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const MissRoute = MissRouteImport.update({
  id: '/miss',
  path: '/miss',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatIdRoute = CandidatIdRouteImport.update({
  id: '/candidat/$id',
  path: '/candidat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentConfirmationRoute = PaymentConfirmationRouteImport.update({
  id: '/payment/confirmation',
  path: '/payment/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMonetbilWebhookRoute = ApiMonetbilWebhookRouteImport.update({
  id: '/api/monetbil/webhook',
  path: '/api/monetbil/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPayunitWebhookRoute = ApiPayunitWebhookRouteImport.update({
  id: '/api/payunit/webhook',
  path: '/api/payunit/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/vote': typeof VoteRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/payment/confirmation': typeof PaymentConfirmationRoute
  '/api/monetbil/webhook': typeof ApiMonetbilWebhookRoute
  '/api/payunit/webhook': typeof ApiPayunitWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/vote': typeof VoteRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/payment/confirmation': typeof PaymentConfirmationRoute
  '/api/monetbil/webhook': typeof ApiMonetbilWebhookRoute
  '/api/payunit/webhook': typeof ApiPayunitWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/classement': typeof ClassementRoute
  '/master': typeof MasterRoute
  '/miss': typeof MissRoute
  '/vote': typeof VoteRoute
  '/candidat/$id': typeof CandidatIdRoute
  '/payment/confirmation': typeof PaymentConfirmationRoute
  '/api/monetbil/webhook': typeof ApiMonetbilWebhookRoute
  '/api/payunit/webhook': typeof ApiPayunitWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/classement'
    | '/master'
    | '/miss'
    | '/vote'
    | '/candidat/$id'
    | '/payment/confirmation'
    | '/api/monetbil/webhook'
    | '/api/payunit/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/classement'
    | '/master'
    | '/miss'
    | '/vote'
    | '/candidat/$id'
    | '/payment/confirmation'
    | '/api/monetbil/webhook'
    | '/api/payunit/webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/classement'
    | '/master'
    | '/miss'
    | '/vote'
    | '/candidat/$id'
    | '/payment/confirmation'
    | '/api/monetbil/webhook'
    | '/api/payunit/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ClassementRoute: typeof ClassementRoute
  MasterRoute: typeof MasterRoute
  MissRoute: typeof MissRoute
  VoteRoute: typeof VoteRoute
  CandidatIdRoute: typeof CandidatIdRoute
  PaymentConfirmationRoute: typeof PaymentConfirmationRoute
  ApiMonetbilWebhookRoute: typeof ApiMonetbilWebhookRoute
  ApiPayunitWebhookRoute: typeof ApiPayunitWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classement': {
      id: '/classement'
      path: '/classement'
      fullPath: '/classement'
      preLoaderRoute: typeof ClassementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miss': {
      id: '/miss'
      path: '/miss'
      fullPath: '/miss'
      preLoaderRoute: typeof MissRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidat/$id': {
      id: '/candidat/$id'
      path: '/candidat/$id'
      fullPath: '/candidat/$id'
      preLoaderRoute: typeof CandidatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/confirmation': {
      id: '/payment/confirmation'
      path: '/payment/confirmation'
      fullPath: '/payment/confirmation'
      preLoaderRoute: typeof PaymentConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/monetbil/webhook': {
      id: '/api/monetbil/webhook'
      path: '/api/monetbil/webhook'
      fullPath: '/api/monetbil/webhook'
      preLoaderRoute: typeof ApiMonetbilWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payunit/webhook': {
      id: '/api/payunit/webhook'
      path: '/api/payunit/webhook'
      fullPath: '/api/payunit/webhook'
      preLoaderRoute: typeof ApiPayunitWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ClassementRoute: ClassementRoute,
  MasterRoute: MasterRoute,
  MissRoute: MissRoute,
  VoteRoute: VoteRoute,
  CandidatIdRoute: CandidatIdRoute,
  PaymentConfirmationRoute: PaymentConfirmationRoute,
  ApiMonetbilWebhookRoute: ApiMonetbilWebhookRoute,
  ApiPayunitWebhookRoute: ApiPayunitWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
